services:
  core:
    build: .
    image: ghcr.io/uafilms/core:latest
    container_name: uafilms-core
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      # - JWT_SECRET=change_to_a_random_secret_string
      # - TMDB_TOKEN=your_tmdb_token_here
    volumes:
      - ./cache:/app/cache
